services:
  postgres:
    image: postgres:18
    container_name: practice_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Practise/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: practice_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "10000:10000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 10000

      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}

      Storage__Endpoint: minio:9000
      Storage__AccessKey: ${MINIO_ROOT_USER}
      Storage__SecretKey: ${MINIO_ROOT_PASSWORD}
      Storage__Bucket: ${MINIO_BUCKET}
      Storage__UseSsl: "false"
      Storage__PublicBaseUrl: http://localhost:9000/${MINIO_BUCKET}

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}

      Email__Smtp__Host: ${SMTP_HOST}
      Email__Smtp__Port: ${SMTP_PORT}
      Email__Smtp__Username: ${SMTP_USERNAME}
      Email__Smtp__Password: ${SMTP_PASSWORD}
      Email__Smtp__FromEmail: ${SMTP_FROM_EMAIL}
      Email__Smtp__FromName: ${SMTP_FROM_NAME}
      Email__Smtp__EnableSsl: "true"

      EmailConfirmation__PublicApiBaseUrl: ${PUBLIC_API_BASE_URL}
      EmailConfirmation__FrontendResultUrl: ${FRONTEND_RESULT_URL}
      OwnerRegistration__InviteToken: ${OWNER_INVITE_TOKEN}
      ShareLinks__PublicBaseUrl: ${PUBLIC_API_BASE_URL}

  minio:
    image: minio/minio
    container_name: minio_practice
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: